// <auto-generated />
using System;
using System.Collections.Generic;
using Bakery2048.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bakery2048.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205131736_RemovePowerUps")]
    partial class RemovePowerUps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bakery2048.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<int>("BestTileAchieved")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FavoriteItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("HighestScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<List<string>>("PowerUpHistory")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("PowerUpsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMoves")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TotalPlayTime")
                        .HasColumnType("interval");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WinStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialItem")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TileValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Color = "#fcefe6",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(240),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(270),
                            Icon = "🌾",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Flour",
                            TileValue = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Color = "#f2e8cb",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(300),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(310),
                            Icon = "🥚",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Egg",
                            TileValue = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Color = "#f5b682",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(310),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(310),
                            Icon = "🧈",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Butter",
                            TileValue = 8
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Color = "#f29446",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(310),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(310),
                            Icon = "🍬",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Sugar",
                            TileValue = 16
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Color = "#f88973",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(320),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(320),
                            Icon = "🍩",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Donut",
                            TileValue = 32
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Color = "#ed7056",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(320),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(320),
                            Icon = "🍪",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Cookie",
                            TileValue = 64
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Color = "#ede291",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(330),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(330),
                            Icon = "🧁",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Cupcake",
                            TileValue = 128
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Color = "#fce130",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(330),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(330),
                            Icon = "🍰",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Slice Cake",
                            TileValue = 256
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Color = "#ffdb4a",
                            DateCreated = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(330),
                            DateModified = new DateTime(2025, 12, 5, 21, 17, 36, 409, DateTimeKind.Utc).AddTicks(340),
                            Icon = "🎂",
                            IsActive = true,
                            IsSpecialItem = false,
                            ItemName = "Whole Cake",
                            TileValue = 512
                        });
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.HasOne("Bakery2048.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
